name: get_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Kit
  getwidget: ^2.0.5
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  # 网络库
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  # lru网络缓存
  dio_cache_interceptor: ^3.2.6
  # KV存储
  mmkv: ^1.2.14
  # 日志输出
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  # logger_flutter: ^0.7.1
  # H5能力
  webview_flutter: ^3.0.2
  # 权限处理
  permission_handler: ^9.2.0
  # 下拉刷新组件
  pull_to_refresh: ^2.0.0
  # 应用/系统信息
  #package_info_plus: ^1.4.2
  device_info_plus: ^3.2.3
  # 网络状态信息
  connectivity_plus: ^2.3.0
  # 状态管理
  provider: ^6.0.2
  # json注解标记
  json_annotation: ^4.5.0
  # 加解密工具
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image/